name: Charles Warren Product Design
favicon: null
layout_spectrum: 0.26626
typography_spectrum: 0.89528
title: "Charles Warren's online portfolio"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#36bee5'
    - '#207adf'
    - '#3dd7e6'
    - '#bbe3f6'
  brandStrength: 0.5
  lightness: 0.875
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
