typography_spectrum: 1
color:
  brandColors:
    - '#ffffff'
    - '#36bee5'
    - '#207adf'
    - '#3dd7e6'
    - '#bbe3f6'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0
analytics:
  google: null
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/cfe3ff7a-80b5-470f-8a41-6275f1d816e7.png
name: Charles Warren Product Design
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: IDEO 2001-2006
    id: c4aa8806-8bee-4713-b2ac-cc064668e42f
    type: content
  - name: Google Mobile 2007-2010
    id: 59eb9ba2-e103-46f0-8423-0ebd88f063f2
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/c94ac316-e3cd-4293-9352-4284ae02d4e5.png
title: Product Designer Charles Warren's Portfolio. 2001-2016
description: >-
  Designing powerful, beautiful products for work and life, and leading the
  teams that deliver them.
purpose: []
