typography_spectrum: 1
color:
  brandColors:
    - '#ffffff'
    - '#36bee5'
    - '#207adf'
    - '#3dd7e6'
    - '#bbe3f6'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0
analytics:
  google: null
  facebook: null
  twitter: null
name: Charles Warren Product Design
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Product Designer Charles Warren's Portfolio. 2001-2016
description: >-
  Designing powerful, beautiful products for work and life, and leading the
  teams that deliver them.
purpose: []
