name: Charles Warren Product Design
favicon: null
layout_spectrum: 0
typography_spectrum: 1
title: Product Designer Charles Warren's Portfolio. 2001-2016
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#36bee5'
    - '#207adf'
    - '#3dd7e6'
    - '#bbe3f6'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
